CREATE TABLE "Usuario" (
	"dniUsuario" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombreUsuario" VARCHAR(50) NOT NULL,
	"correoUsuario" VARCHAR(70) NOT NULL,
	"fechaRegistro" DATE NOT NULL,
	PRIMARY KEY("dniUsuario")
);




CREATE TABLE "Publicacion" (
	"idPublicacion" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tituloPublicacion" VARCHAR(70) NOT NULL,
	"cuerpoPublicacion" TEXT NOT NULL,
	"fechaPublicacion" DATE NOT NULL,
	PRIMARY KEY("idPublicacion")
);



ALTER TABLE "Usuario"
ADD FOREIGN KEY("dniUsuario") REFERENCES "Publicacion"("idPublicacion")
ON UPDATE NO ACTION ON DELETE NO ACTION;